### ISSUE TITLE
Generating CSS bundle if import more than one stylesheet

### ISSUE THREAD

**Issue by subz390** [jleeson/rollup-plugin-import-css#1]
Hi Jacob,
I have an issue to report with your Rollup plugin 👍🏻 

## ISSUE
I'm getting a CSS bundle generated when importing more than one stylesheet and all to variables, like so...
```js
import commonstyle from './commonstyle.css'
import bookstyle from './bookstyle.css'
import docstyle from './docstyle.css'
```

In the referenced code below, a newline is added for each file even if it's assigned a variable.  So when testing css length it will always be greater than zero.
https://github.com/jleeson/rollup-plugin-import-css/blob/fef6dc35002aa83d5c0191af92c712cdd736beac/src/index.js#L50-L52

## SOLUTION
Adding a `trim()` will remove the newline in an otherwise empty string if all files were assigned a variable.  And where multiple files with no assigned variables, it'll trim the last newline off the end of the string.
```js
if(css.trim().length <= 0 && !alwaysOutput) return;
```

**Comment by jleeson** [comment]
Hi @subz390 , thanks for making this issue. Since you have provided a solution to the problem already, would you like to make the change and submit a pull request? If not I can apply your fix that and release an update later today.

**Comment by subz390** [comment]
Sure ok I'll sort out a PR tomorrow as it's UK time here.  If it was a critical bug I'd say go ahead and patch it now to save time.
