### ISSUE TITLE
Node version error after upgrade to latest version

### ISSUE THREAD

**Issue by majoncas-ue** [jleeson/rollup-plugin-import-css#13]
Hello,

After upgrading to the latest version, I am getting this error:

`error rollup-plugin-import-css@3.3.0: The engine "node" is incompatible with this module. Expected version "^16". Got "18.16.0"`

Is there any workaround? I dont want downgrade to node 16 obviously...

Thank you in advance!

**Comment by jleeson** [comment]
Thanks for making a PR for this, it should now be resolved in v3.3.1

**Comment by majoncas-ue** [comment]
Thank you so much!
