### ISSUE TITLE
Rollup 4 support

### ISSUE THREAD

**Issue by rallets** [jleeson/rollup-plugin-import-css#17]
Hi, it looks like Rollup 4 is not listed in the `peerDependencies`. However I'm using it with 4.0.2 without problems. Do you mind extending the version range so I can get rid of the warning and skip the `--force` install option?
Thank you

**Comment by crisward** [comment]
Also tried with 4.* and seems to work fine.

**Comment by crisward** [comment]
FWIW I've opened a pull request. I'd imagine you'd want to check the rollup api updates before pushing. 😬

**Comment by jleeson** [comment]
Thanks @rallets for opening this issue and @crisward for creating the PR. I double checked the Rollup v4 migration guide and this plugin requires no changes. I went ahead and merged the PR and pushed an update (v3.3.5) for this plugin.
