### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'importedIds')

### ISSUE THREAD

**Issue by DaniilSkLi** [jleeson/rollup-plugin-import-css#21]
Error:
```
[!] (plugin import-css) TypeError: Cannot read properties of null (reading 'importedIds')
    at getRecursiveImportOrder (file:///home/daniilskli/My/projects/web/project/node_modules/rollup-plugin-import-css/dist/plugin.js:15:22)
    at Object.generateBundle (file:///home/daniilskli/My/projects/web/project/node_modules/rollup-plugin-import-css/dist/plugin.js:56:25)
    at /home/daniilskli/My/projects/web/project/node_modules/rollup/dist/shared/rollup.js:1005:40
```

`rollup.config.js`
```js
import { chromeExtension, simpleReloader } from 'rollup-plugin-chrome-extension';
import { babel } from '@rollup/plugin-babel';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import eslint from '@rollup/plugin-eslint';
import terser from '@rollup/plugin-terser';
import css from 'rollup-plugin-import-css';
import postcss from 'rollup-plugin-postcss';
import del from 'rollup-plugin-delete';

export default {
  input: 'src/manifest.json',
  output: {
    dir: 'dist',
    format: 'iife',
  },
  plugins: [
    del({ targets: 'dist' }),
    chromeExtension(),
    simpleReloader(),
    nodeResolve(),
    commonjs(),
    babel({
      babelHelpers: 'runtime',
      plugins: [
        ['@babel/plugin-transform-runtime', { useESModules: true }],
      ],
    }),
    css(),
    postcss(),
    eslint(),
    terser(),
  ],
};
```

I've tried changing the order of plugins or disabling unnecessary ones, but I still get this error. Even the css is not included anywhere and I still get the error. I Googled the error, but didn't really find any solution.

**Comment by jleeson** [comment]
HI @DaniilSkLi, what version of rollup are you using and which version of this plugin?

**Comment by DaniilSkLi** [comment]
Hi @jleeson. I am using rollup latest version 4.9.6 and also this package latest version 3.4.0. I tried rolling back the rollup to the latest 3, but everything was the same.

I have installed plugin version 3.3.5 with 4.9.6 rollup as well as 3.29.4, nothing changes. I also deleted yarn.lock and the node_modules folder to be sure.

**Comment by jleeson** [comment]
Thanks for testing that, It looks like this is a problem with using the extension with your manifest.json as the entryChunk. This plugin is trying to find the import order of the css files but is unable to do so starting from a json file. I look at adding support for this over the weekend.

**Comment by DaniilSkLi** [comment]
Thank you. Will wait

**Comment by jleeson** [comment]
Hi @DaniilSkLi, apologies for the delay on a fix for this. It required more investigation than I had originally anticipated. It looks like the chrome extension plugin is outputting the entry files from the manifest without the data thats required to determine the order of css imports. I was able to get this error on rollup-plugin-postcss as well when using the extract mode (similar to the default mode of this plugin).

It looks like the only option to use css with the chrome extension plugin is to either specify your static assets in the chrome manifest.json file as their docs suggest or you can use a different css import mode. I have adjusted this plugin to support three options while working with the chrome extension plugin. Make sure you update to v3.5.0.

The first option you can do is import the css file normally ex: `import "./styles.css";` and add the new `inject: true` option to the plugin, this will import the css and inject it into the document head at runtime. (this is how most css plugins work)

Alternatively you can import the css as a variable or use the `modules` option to use native css modules` ex: `import styles from "./styles.css";` from there, you can do what you want with the css source in js.

The only limitation is that the chrome extension plugin does not make it possible to emit an accurate css bundle. So the inject option would be the closest method to what you are probably looking for.

Hopefully that resolves the issue for you. Feel free to open another issue if you run into further problems.
