### ISSUE TITLE
CSS files are joined and minified correctly, but not imported in the js file 

### ISSUE THREAD

**Issue by hsbsid** [jleeson/rollup-plugin-import-css#22]
I am using this package to join and minify the css imports in my index.js file. Upon compiling, a new css file is created, it has the correct CSS. However, this file does not get imported into the index.js in build.

e.g. My src index.js file has imports:
`import 'a.css';
import 'b.css';`

in my rollupjs config:
`plugins: [ css({alwaysOutput:true, minify:true,  modules:true})]`

upon running `rollup -c` I get a new css file in the build directory under the assets folder. the file is a correct merger of a.css and b.css

but my index.js which is being built by rollup.js no longer imports this new css file.

**Comment by jleeson** [comment]
Hello, This behavior is to be expected. the imports are being processed by the plugin and thus are removed from the bundle. If you would like to have your processed js bundle to have an import to the css bundle, you can do so by manually specifying the import statement using rollup's `output.banner` option.
