### ISSUE TITLE
The Minification Problem

### ISSUE THREAD

**Issue by rez1dent3** [jleeson/rollup-plugin-import-css#28]
Hello. When I said that the problem was in the plugin @babel/plugin-syntax-import-attributes, I simply forgot to update your package. I checked on version 3.5.1 :there should be a picture of harold here:

Revert revert: https://github.com/bavix/uuid-ui/pull/203

My imports:
```javascript
import '@creativebulma/bulma-tooltip/dist/bulma-tooltip.css'
import 'bulma/css/bulma.css'
import './app.css'
//...
import "@theme-toggles/react/css/Expand.css"
```

diff: https://www.diffchecker.com/ck0onuCe/

Was / became:
<img width="1296" alt="Screenshot 2024-09-25 at 23 21 36" src="https://github.com/user-attachments/assets/10341fb8-774d-4931-a465-ceb7c3df58d2">

_Originally posted by @rez1dent3 in https://github.com/jleeson/rollup-plugin-import-css/issues/27#issuecomment-2375180434_

**Comment by rez1dent3** [comment]
@jleeson FYI

**Comment by rez1dent3** [comment]
https://github.com/jleeson/rollup-plugin-import-css/issues/27#issuecomment-2375186159

**Comment by jleeson** [comment]
Thank you, I will work on a solution to the minifier this week.

**Comment by rez1dent3** [comment]
You can use my project as a demo if you need to playground it.

Branch: revert-202-revert-201-upgrade-rollup-plugin-import-css

Launch:
```sh
npm run dev
```

**Comment by jleeson** [comment]
@rez1dent3, I have updated the minifyCSS function to properly stripe whitespace without breaking the styling rules. Give v3.5.3 a try and let me know if that resolves it for you.

**Comment by rez1dent3** [comment]
Expectation: https://bavix.github.io/uuid-ui/

Reality:
<img width="1359" alt="Screenshot 2024-09-26 at 08 44 59" src="https://github.com/user-attachments/assets/224016cd-2b37-45fd-a182-0b2ac0aa2452">

**Comment by jleeson** [comment]
I thought my test covered all use cases, but it appears I thought wrong. Sorry for the inconvenience, I will work on a better fix today.

**Comment by jleeson** [comment]
@rez1dent3 can you please update to v3.5.4 and let me know if that solves the problem? I implemented a new minifer from scratch instead of trying to modify the original implementation which was broken in several ways. I have tested this version in the branch you listed for your project and it is matching the expected result you outlined.

**Comment by rez1dent3** [comment]
Yes, this solved my problem. Thank you.
