### ISSUE TITLE
ASK - What is the difference of this plugin compared to rollup-plugin-css-only?

### ISSUE THREAD

**Issue by lamualfa** [jleeson/rollup-plugin-import-css#3]
I am sorry. This plugin is good. But, there are [another plugin](https://github.com/thgh/rollup-plugin-css-only) with the same functionality. What is your motivation for making this plugin? 

If there is a difference between the both plugin, please affirm the differences in `README.md` file. Some people little confused to choose between the two.

**Comment by jleeson** [comment]
Hi @lamualfa, there is a difference between the plugins. This plugin lets you import your css as a variable and import it to be written to a css bundle. The plugin you mentioned is only capable of importing css to be written to a css bundle. The functionality is similar but this plugin adds some extra functionality. There are however other plugins that offer this functionality as well but they often include a lot of dependencies while this one does not. I believe the README already states what features this plugin enables but i can add something comparing it to the plugin you mentioned.
