### ISSUE TITLE
Have an option to list specific output even with preserveModules

### ISSUE THREAD

**Issue by malaudha** [jleeson/rollup-plugin-import-css#32]
I'm in a specific case where I want rollup to follow the `preserveModules `directive and keep my folder structure but I want the stylesheet to be output in a specific folder and not follow the `preserveModules `instructions. 
Example: 
```
src/
  dist/
  scripts/
    modules/
      file.js with import styles from ../dist/styles.css" assert { type: "css" };
    lib/
  styles/
```

Scripts should be output following folders structure but I need the styles.css to be at the root of dist/ (currently it will output another "dist" folder in "dist")

**Comment by jleeson** [comment]
@malaudha after looking more into this, I have a few questions. 

1. are you manually writing the style imports to be resolved to the specific output folder or do you expect this plugin to change the import path?

2. Can you provide the rollup config you are using so I can get an accurate idea of how you are expecting the styles to be output?

**Comment by jleeson** [comment]
As of v3.5.7, this plugin will ignore the preserveModules option when the plugin's output option is specified. this will allow you to specify the location of the bundled css file and continue to have your javascript respect the preserveModules option.

**Comment by malaudha** [comment]
Oh thanks, I had in mind I needed to provide my previous config, sorry I didn't have much time to help you sooner!

**Comment by jleeson** [comment]
No worries, I hope this solution works for your use case.
