### ISSUE TITLE
Is there a CHANGELOG?

### ISSUE THREAD

**Issue by mksglu** [jleeson/rollup-plugin-import-css#7]
Hi everytone,

I'm using version `2.0.1,` and I want to upgrade to the latest, but I can not find any changelog about that. IDK if it's broken my custom npm package. So, is there any changelog to review?

Thanks.

**Comment by jleeson** [comment]
Hey @mksglu, there is no changelog (will be adding one moving forward, thanks for brining this to my attention)
between v2.0.1 and v3, there should be no api changes, there were a few changes internally to fix bugs such as maintaining the order the css was imported and ensuring code splitting worked properly. Other than that, nothing changed that should break your code. 

If you want to share a code snippet or create a minimal reproduction, I would love to take a look and help you get the latest version working for you.

**Comment by mksglu** [comment]
> 

Thanks for the quick reply. I'll bump the version to the latest. 

Thanks again for the package.
