### ISSUE TITLE
Error: e.transform is not a function

### ISSUE THREAD

**Issue by kdmcguire** [jleeson/rollup-plugin-import-css#8]
Hello! I'm using rollup-plugin-import-css in a component library to bundle some css files from fontsource into a single fonts.css file in /dist.

In the generated fonts.css file, all of the font urls are set as "./files/(font file)", but I'd like this to be "./fonts/(font name)/(font file)".

I'm trying to use the transform option to change this, but am encountering an error.

Out code:

```js
{
    input: "dist/types/index.d.ts",
    output: [{ file: "dist/index.d.ts", format: "esm" }],
    plugins: [
      commonjs(),
      dts(),
      resolve(),
      css({
        input: [
          "@fontsource/inter/400.css",
          "@fontsource/inter/600.css",
          "@fontsource/inter/700.css",
        ],
        transform: [{ "./files/inter": "./fonts/inter/inter" }],
        output: "fonts.css",
      }),
    ],
  },
```

And the response:

```
dist/types/index.d.ts → dist/index.d.ts...
[!] (plugin import-css) TypeError: e.transform is not a function
node_modules/@fontsource/inter/600.css
TypeError: e.transform is not a function
    at Object.transform (C:\Users\kmcguire\Repos\component-library\node_modules\rollup-plugin-import-css\dist\plugin.js:1:542)
    at C:\Users\kmcguire\Repos\component-library\node_modules\rollup\dist\shared\rollup.js:22779:37
```

**Comment by jleeson** [comment]
Hey @kdmcguire, the `transform` option must be a function, it does not process replacing strings for you automatically as the `transform` option is designed to allow any kind of processing that this plugin does not do out of the box.

here is modified code that should give you the expected output. Let me know if this works for you!
```js
{
    input: "dist/types/index.d.ts",
    output: [{ file: "dist/index.d.ts", format: "esm" }],
    plugins: [
      commonjs(),
      dts(),
      resolve(),
      css({
        input: [
          "@fontsource/inter/400.css",
          "@fontsource/inter/600.css",
          "@fontsource/inter/700.css",
        ],
        transform: (code) => code.replaceAll("./files/inter", "./fonts/inter/inter"),
        output: "fonts.css",
      }),
    ],
  },
```

**Comment by kdmcguire** [comment]
That does it! Thank you!

Cheeky follow-up Q: how would you do this a second time, for another font?

**Comment by jleeson** [comment]
@kdmcguire you should be able to modify the transform function to do as many transforms as you like. the `transform` option takes a function that returns a string, so any string modifications will work.

**Example**
```js
transform: (code) => {
    const transform1 = code.replaceAll("./files/inter", "./fonts/inter/inter");
    const transform2 = transform1.replaceAll({"./files/myotherfile", "./fonts/myotherfile/myotherfile");
    return transform2;
},
```

You can do whatever modifications you want in the transform function as long as it returns a string.

**Comment by jleeson** [comment]
Im assuming you were able to get this working so ill go ahead and close this issue. If you have more problems feel free to open a new issue or this one can be reopened.

**Comment by kdmcguire** [comment]
Hello! Sorry, we've been having a slew of issues with what we're trying to do, and I wasn't sure what was me doing something wrong vs. trying to do the wrong thing entirely, so I didn't want to bother you!

When I tried this

```
transform: (code) => {
    const transform1 = code.replaceAll("./files/inter", "./fonts/inter/inter");
    const transform2 = transform1.replaceAll("./files/myotherfile", "./fonts/myotherfile/myotherfile");
    return transform2;
},
```

I started getting errors about the unexpected '@' in the '@font-face' for the second font

```
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
node_modules/@fontsource/material-icons/index.css (2:0)
1: /* material-icons-base-400-normal*/
2: @font-face {
   ^
3:   font-family: 'Material Icons';
4:   font-style: normal;
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
```

We're in the middle of trying to make our component library provide the fonts we want for the front-end app that will use it, we'd prefer to stick with fontsource as the font supplier if possible... But it's proven tricky so far!

**Comment by jleeson** [comment]
@kdmcguire, that error is usually caused by a plugin trying to process the imported css files as js files. Do you have any other plugins processing imports before `rollup-plugin-import-css`. If so try moving the css plugin to handle processing first.

**Comment by kdmcguire** [comment]
The css plugin is first in the list for this job, and I also tried moving this job to first (instead of second) but saw the same result.

Here's the whole file, in case I'm missing anything important! Appreciate your help here - don't hesitate to tell me when it stops being a css plugin problem.

```js
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "rollup-plugin-typescript2";
import postcss from "rollup-plugin-postcss";
import dts from "rollup-plugin-dts";
import copy from "rollup-plugin-copy";
import json from "@rollup/plugin-json";
import css from "rollup-plugin-import-css";
import pkg from "./package.json";

export default [
  {
    input: "src/index.ts",
    output: [
      {
        file: pkg.main,
        format: "cjs",
        sourcemap: true,
      },
      {
        file: pkg.module,
        format: "esm",
        sourcemap: true,
      },
    ],
    plugins: [
      resolve(),
      commonjs(),
      typescript({ tsconfig: "./tsconfig.json" }),
      postcss(),
      copy({
        targets: [
          { src: "./src/theme/fonts", dest: "./dist" },
          {
            src: "./node_modules/@fontsource/inter/files",
            dest: "./dist/fonts",
          },
          {
            src: "./node_modules/@fontsource/material-icons/",
            dest: "./dist/fonts",
          },
        ],
      }),
      json(),
    ],
    external: ["react", "react-dom"],
  },
  {
    input: "dist/types/index.d.ts",
    output: [{ file: "dist/index.d.ts", format: "esm" }],
    plugins: [
      css({
        include: [
          "node_modules/@fontsource/inter/400.css",
          "node_modules/@fontsource/inter/600.css",
          "node_modules/@fontsource/inter/700.css",
          "node_modules/@fontsource/material-icons/base.css",
        ],
        transform: (code) => {
          const transform1 = code.replaceAll(
            "./files/inter",
            "./fonts/inter/inter"
          );
          const transform2 = transform1.replaceAll(
            "./files/material-icons",
            "./fonts/material-icons/material-icons"
          );
          return transform2;
        },
        output: "fonts.css",
      }),
      dts(),
      resolve(),
    ],
    external: ["react", "react-dom"],
  },
];
```

**Comment by jleeson** [comment]
looking at your config and the error you are receiving, it looks like this could be coming from the usage of `rollup-plugin-postcss` not `rollup-plugin-import-css` (correct me if im wrong). the typescript plugin is processing the imports and trying to treat the css imports as js files. try moving the postcss plugin above the  typescript plugin so that the css gets processed first. you may also need to tell typescript to ignore imports that resolve to css files.

Also as a side note, what are your usecases for using both `rollup-plugin-postcss` and `rollup-plugin-import-css`, does this plugin lack a feature the other provides?

**Comment by kdmcguire** [comment]
Hey again! Sorry for the gap. In the end, we decided not to try to bundle the fonts with rollup at all, and instead list them as dependencies rather than devDependencies and then import them in our consumer front-end app. Not quite as hand-holdy as we were hoping for but we couldn't work out some last kinks we were stuck on, including something unrelated to this plugin.

(E.g. Even when we were providing one of the fonts correctly with the method you described, Next.js was still looking for that same font at /files/fontname as well as the path we told it to. And we couldn't work out why!)

Thank you for your time and effort, though! It was appreciated.
