### ISSUE TITLE
update support for rollup v3

### ISSUE THREAD

**Issue by michaelfaith** [jleeson/rollup-plugin-import-css#9]
Rollup v3 was released [a couple weeks ago](https://github.com/rollup/rollup/releases/tag/v3.0.0).  The plugin currently has ^2.x.x in the peer dependencies.

**Comment by jleeson** [comment]
Thanks for opening this issue @michaelfaith, I have updated the plugin to support Rollup v3. You can upgrade to v3.1.0 of this plugin and you should be good to go.

**Comment by michaelfaith** [comment]
@jleeson thanks for the quick work!
